[workspace]
members = [
    "balter",
    "balter-core",
    "balter-runtime",
    "balter-macros",
    "tests",
    "mock-service",
    "examples",
]

exclude = [
    "benchmark",
    "playground",
]

resolver = "2"
