[workspace]
members = [
    "balter-core",
    "balter-macros",
    "mock-service",
    "examples/*",
]

exclude = [
    "balter-benchmark",
    "playground",
    "rust-talk-feb-2024",
]

resolver = "2"
