[package]
name = "mock-service"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.18"
tokio = { version = "1.29.1", features = ["full"] }
governor = "0.6.0"
lazy_static = "1.4.0"
metrics = "0.22.0"
metrics-exporter-prometheus = "0.13.0"
